### ISSUE TITLE
Create and document deployment procedure

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/yinyo#110]
I'm imagining three sets of deployment instructions:

* Suggested production deployment
* Test deployment (for eg sysadmins evaluating yinyo)
* Dev test for developers working on Yinyo server (already handled in README.md)

We may not need all of these for the first launch.

Required for #109.

**Comment by mlandauer** [comment]
Not an issue so more as we're setting up a production instance that can be used by other people
