### ISSUE TITLE
Add a way for users to keep informed of developments with the project

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/yinyo#142]
This could be a mailing list for instance.

**Comment by mlandauer** [comment]
Do we sign them up to a Campaign Monitor list? Is this going to cost us $$?

**Comment by jamezpolley** [comment]
CM's usual charges are based on the total number of recipients, which in our case is around 75k. The charges for this are... somewhere about 419AUD/month for the most basic plan.

We can instead pay a per-mailout fee which is based on the number of recipients of the mailout; this would be much smaller - $7 per mailout + 1.4c/recipient.

**Comment by jamezpolley** [comment]
My suggestion would be a category on Discourse; which combines web forum features (for people who like that) with email notifications and replies (for people who prefer to use it as a mailing list) *and* has integration with Github to make it easy for people to link to issues/PRs etc.

We could use help.morph.io for this (but if we did, we might want to tweak it to not require a Morph account to log in - we could perhaps use Github login directly instead). Alternatively, I've got ansible and terraform setup ready to go to set up a new discourse instance

**Comment by mlandauer** [comment]
I think this issue is too vague at the moment to be useful. Also, we don't have a development community yet, so it's hard to even begin to guess what the needs are. So, closing this.
