### ISSUE TITLE
Use CI/CD to produce prebuilt binary

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/yinyo#89]
This is useful for people who are not interested in developing but want to use the API as a user

**Comment by jamezpolley** [comment]
We now have this happening for every commit (build artifacts produced by actions - eg, see https://github.com/openaustralia/yinyo/commit/6e7b26d13dbbfd98a4e1a01ad34b42f2b1733296/checks?check_suite_id=411206212) as well as automatically for every [release](https://github.com/openaustralia/yinyo/releases/) (eg see https://github.com/openaustralia/yinyo/releases/tag/v0.9-beta.1)
